spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Groupo
    username: JAs0nDev
    password: Zjx0319*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080
  error:
    include-message: never
    include-binding-errors: never

app:
  jwt:
    secret: "0123456789_0123456789_0123456789_0123456789_012345"
    access-exp-min: 30      # 访问令牌 30 分钟
    refresh-exp-days: 7     # 刷新令牌 7 天